config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :users, only: [:index, :create, :show]
  #   resources :evaluations, only: [:index, :create]
  #   resources :friendship, only: [:create]
  # end


  resources :communities, only: [:index, :show, :searches] do
    resources :posts, only: [:index, :new, :create]
    resources :matches, only: [:index, :create]
    post 'join', to: 'memberships#join' , as: 'member'
  end
  resources :users, only: [:edit, :update]
  get '/profile/:id', to: 'pages#profile', as: 'profile'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  resources :posts, only: [:destroy]
end

app/views/pages/404.html.erb
<h1>404 Not Found!</h1>

app/views/pages/500.html.erb
<h1>Errors#internal_server_error</h1>
<p>Find me actual error page in app/views/errors/internal_server_error.html.erb</p>

app/views/pages/about.html.erb
<h1>About Gamesphere</h1>
<p>testing view</p>

app/views/pages/home.html.erb
<title>.:. Home .:. GameSphere .:.</title>

  <div class="bg-image">
    <% content_for(:navbar_class, "navbar-home") %>
    <div class="banner">
      <div class="container">
        <h1>GameSphere</h1>
        <p>
        <span class="typed-header"></span>
        <span class="typed-cursor"></span>
        </p>
      </div>
    </div>
    <div>
      <%= link_to "Discover", communities_path, class: "sphere-btn" %>
    </div>
    <div class="about-icons">
      <div class="join-icon">
        <%# <%= link_to("communities/1/posts") do %>
        <i class="fas fa-gamepad"></i><h3>Join a community of players that can improve your game experience.<h3>
        <%# <% end %>
      </div>
      <div class="match-icon">
      <i class="fas fa-user-friends"></i><h3>Match with players that have the same rank and common interests as you do!</h3>
      </div>
      <div class="chat-icon">
      <i class="fas fa-network-wired"></i><h3>Chat, find players and become active in your favorite game communities.</h3>
      </div>
    </div>
    <div class="cards-container">
      <div class="cards">
        <div class="card-lol">
            <h3> League of Legends </h3>
                    <a href="#">
            <span></span>
            <span></span>
            <span></span>
            JOIN
          </a>
        </div>

        <div class="card-dota">
          <h3> Dota 2 </h3>
                    <a href="#">
            <span></span>
            <span></span>
            <span></span>
            JOIN
          </a>
        </div>

        <div class="card-fortnite">
          <h3> Fortnite </h3>
                    <a href="#">
            <span></span>
            <span></span>
            <span></span>
            JOIN
          </a>
        </div>

        <div class="card-valorant">
          <h3> Valorant </h3>
                    <a href="#">
            <span></span>
            <span></span>
            <span></span>
            JOIN
          </a>
        </div>

        <div class="card-gta">
          <h3> Grand Theft Auto V </h3>
                    <a href="#">
            <span></span>
            <span></span>
            <span></span>
            JOIN
          </a>
        </div>

        <div class="card-wow">
          <h3> World of Warcraft </h3>
                    <a href="#">
            <span></span>
            <span></span>
            <span></span>
            JOIN
          </a>
        </div>

      </div>
    </div>

    <div style="margin: 50px;"></div>

    <footer>
      <div class="row">
        <div class="col"">
          <p>LOGO</p>
        </div>

        <div class="col">
          <h3>Office <div class="underline"><span></span></div></h3>
          <p>Rio de Janeiro, Rj.</p>
          <p>Brasil</p>
          <p class="company-email">gamersphere@support.com</p>
        </div>

        <div class="col">
          <h3>Links <div class="underline"><span></span></div></h3>
          <ul>
            <li><a href="#"></a>About us</a></li>
            <li><a href="#"></a>Services</a></li>
            <li><a href="#"></a>Features</a></li>
          </ul>
        </div>

        <div class="col">
          <h3>Newsletter <div class="underline"><span></span></div></h3>
          <Newsletter-form>
            <i class="far fa-envelope"></i>
            <input type="email" placeholder="Enter your email" required>
            <button type="submit"><i class="far fa-arrow-alt-circle-right"></i></button>
          </Newsletter-form>
          <div class="social-midia">
          <i href ="#" class="fab fa-fw fa-youtube"></i>
          <i href ="#" class="fab fa-twitter"></i>
          <i href ="#" class="fab fa-linkedin"></i>
          <i href ="#" class="fab fa-whatsapp"></i>
          </div>
        </div>
      </div>
      <hr>
      <p class="copyright">GamerSphere Company © - All Rights Reserved</p>
      <%# <div>Icons made by <a href="https://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div> %>
    </footer>
  </div>

app/views/pages/profile.html.erb
<div class="profile-bg">
  <div class="profile-container">
    <div class="main-body">
      <div class="row gutters-sm">
        <div class="col-md-4 mb-3">
          <div class="card-user-profile">
            <div class="card-user-profile-body">
              <div class="d-flex flex-column align-items-center text-center">
                <%= image_tag(@user.avatar_thumbnail, class: "avatar", width: 150)%>
                <div class="mt-3">
                  <h3><%= @user.username %><h3>
                  <h5 class="mb-1 font-size-md p-2"></h5>
                  <%= link_to "Edit Profile", edit_user_path, class: "btn btn-outline-primary" %>
                  <%= link_to "Communities", communities_path, class: "btn btn-outline-primary" %>
                  <%= link_to "My Friends", "#", class: "btn btn-outline-primary" %>
                </div>
              </div>
            </div>
          </div>
          <%# <div class="card-user-profile mt-3">
            <ul class="list-group list-group-flush">
              <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                <h5 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-globe mr-2 icon-inline"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg>Website</h5>
                <span class="text-secondary">https://bbbbb.com</span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                <h5 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter mr-2 icon-inline text-info"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>Twitter</h5>
                <span class="text-secondary">@bbbbbb</span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                <h5 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-instagram mr-2 icon-inline text-danger"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>Instagram</h5>
                <span class="text-secondary">bbbbbb</span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                <h5 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-facebook mr-2 icon-inline text-primary"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg>Facebook</h5>
                <span class="text-secondary">bbbbbb</span>
              </li>
            </ul>
          </div> %>
        </div>
        <div class="col-md-8">
          <div class="card-user-info mb-3">
            <div class="card-user-profile-info">
              <div class="row">
                <div class="col-sm-3">
                  <h5 class="mb-0">Username :</h5>
                </div>
                <div class="col-sm-9 text-primary">
                  <%= @user.full_name%>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <h5 class="mb-0">Email :</h5>
                </div>
                <div class="col-sm-9 text-primary">
                  <%= @user.email %>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-9 text-primary">
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <h5 class="mb-0">Location :</h5>
                </div>
                <div class="col-sm-9 text-primary">
                  <%= @user.location%>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <h5 class="mb-0">Language :</h5>
                </div>
                <div class="col-sm-9 text-primary">
                  <%= @user.language%>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <h5 class="mb-0">Age :</h5>
                </div>
                <div class="col-sm-9 text-primary">
                  <%= @user.age%>
                </div>
              </div>
              <hr>
              <%# <div class="row">
                <div class="col-sm-12">
                  <a class="btn btn-info " target="__blank" href="#">Edit</a>
                </div>
              </div> %>
            </div>
          </div>


      <div class="row gutters-sm">
        <div class="col-sm-6 mb-3">
          <div class="card-user-attributes h-100">
            <div class="card-user-profile-body">
              <h5 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">Player Status</i></h5>
              <small>Communicability</small>
              <div class="progress mb-3" style="height: 5px">
                <div class="progress-bar bg-primary" role="progressbar"  aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <small>Tilt Resistance</small>
              <div class="progress mb-3" style="height: 5px">
                <div class="progress-bar bg-primary" role="progressbar"  aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <small>Manners</small>
              <div class="progress mb-3" style="height: 5px">
                <div class="progress-bar bg-primary" role="progressbar"  aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <small>Sociability</small>
              <div class="progress mb-3" style="height: 5px">
                <div class="progress-bar bg-primary" role="progressbar"  aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <small>leadership</small>
              <div class="progress mb-3" style="height: 5px">
                <div class="progress-bar bg-primary" role="progressbar"  aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="profile-features">

        <%# <div class="Matches-profile">
          <h3>My Matches</h3>
        </div> %>
        <h2>My Communities</h2>
        <hr>
        <div class="profile-cards-container">
          <div class="profile-cards">
            <% @user.memberships.each do |membership| %>
              <div> <%= link_to image_tag(membership.community.img_url, class: "card-cmt-profile"), community_posts_path(membership.community) %>
                <h3> <%= membership.community.title %> </h3>
              </div>
            <% end %>
          </div>
        </div>

        <%# <div class="card-cmt-profile" style="background-image:linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.2)), url('<%=membership.community.img_url%>

      </div>
    </div>
  </div>
      <footer>
      <div class="row">
        <div class="col"">
          <p>LOGO</p>
        </div>

        <div class="col">
          <h3>Office <div class="underline"><span></span></div></h3>
          <p>Rio de Janeiro, Rj.</p>
          <p>Brasil</p>
          <p class="company-email">gamersphere@support.com</p>
        </div>

        <div class="col">
          <h3>Links <div class="underline"><span></span></div></h3>
          <ul>
            <li><a href="#"></a>Who are we</a></li>
            <li><a href="#"></a>Services</a></li>
            <li><a href="#"></a>Features</a></li>
          </ul>
        </div>

        <div class="col">
          <h3>Newsletter <div class="underline"><span></span></div></h3>
          <Newsletter-form>
            <i class="far fa-envelope"></i>
            <input type="email" placeholder="Enter your email" required>
            <button type="submit"><i class="far fa-arrow-alt-circle-right"></i></button>
          </Newsletter-form>
          <div class="social-midia">
          <i href ="#" class="fab fa-fw fa-youtube"></i>
          <i href ="#" class="fab fa-twitter"></i>
          <i href ="#" class="fab fa-linkedin"></i>
          <i href ="#" class="fab fa-whatsapp"></i>
          </div>
        </div>
      </div>
      <hr>
      <p class="copyright">GamerSphere Company © - All Rights Reserved</p>
    </footer>
</div>