config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :users, only: [:index, :create, :show]
  #   resources :evaluations, only: [:index, :create]
  #   resources :friendship, only: [:create]
  # end


  resources :communities, only: [:index, :show, :searches] do
    resources :posts, only: [:index, :new, :create]
    resources :matches, only: [:index, :create]
    post 'join', to: 'memberships#join' , as: 'member'
  end
  resources :users, only: [:edit, :update]
  get '/profile/:id', to: 'pages#profile', as: 'profile'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  resources :posts, only: [:destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :community
  belongs_to :user
  has_many :comments
  has_one_attached :photo
  validates :content, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def posts
    @community = Community.find[params[:community_id]]
    @post = Post.new
  end

  def index
    @community = Community.find(params[:community_id])
    @posts = Post.where(community: @community).order(created_at: :desc)
    @post = Post.new
  end

  def create
    @community = Community.find(params[:community_id])
    @post = Post.new(post_params)
    # we need `community_id` to associate post with corresponding community
    @post.community = @community
    @post.user = current_user
    @post.save
    redirect_to :action => "index", :id => @community
  end

  def find_community
    @community = Community.find[params[:id]]
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to community_posts_path(@post.community)
  end

  def match
    if @player_one != @player_two
      @player_two
    else
      # no matches today
      redirect matches_path
    end
  end

    private

  def post_params
    params.require(:post).permit(:content, :photo, :video)
  end
end

app/views/posts/index.html.erb
<!-- Modal -->
<!-- <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">You have a match!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar" id="post-avatar" alt="avatar">
        <%# <%= cl_image_tag @player_two.photo.key, height: 200, width: 200, crop: :fill %> %>
        <%# <%= @player_two.username %> %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= link_to "See match", community_matches_path(@community), class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>-->

<div class="main-card card-banner" style='background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), image-url("mf.jpg")'>
  <h1 class="list-title"><%= @community.title %></h1>
  <div class="join-button">
   <%= link_to "Join Community", community_member_path, method: :post, class: "btn btn-outline-secondary" %>
  </div>
</div>
    <div class="league-main">
    </div>
<div class="main-page">
  <div class="sidebar">
    <div class="league-main">
    </div>
    <ul>
      <li><img src="https://res.cloudinary.com/yuhri/image/upload/v1630825667/lolicon_p5keax.png" class="main-league"></li>
      <li><h4><%= link_to "My Profile", profile_path(current_user) %> <h4></li>
      <li><h4> Messages <h4></li>
      <li><h4> Friends <h4></li>
      <li><h4> Matches <h4></li>
    </ul>
  </div>

  <div class="post-msg form-login">
      <% if user_signed_in? %>
    <div class="d-flex justify-content-around">
      <div class="post-form">
        <%= simple_form_for [@community, @post] do |f| %>
          <%= f.input :content %>
          <%= f.input :photo, as: :file%>
          <%= f.input :video, as: :file %>
          <%= f.submit %>
        <% end %>
      </div>
      <img src="https://res.cloudinary.com/yuhri/image/upload/v1630826048/zed_scs6zc.png" class="zed">
      <img src="https://res.cloudinary.com/yuhri/image/upload/v1630826288/vi_meozmu.png" class="vi">
      <img src="https://res.cloudinary.com/yuhri/image/upload/v1631141239/leesin_z6pzmu.png" class="lee-sin">
    </div>
    <hr class="hr">
    <% end %>
    <% @posts.each do |post| %>
      <%= image_tag(post.user.avatar_thumbnail, class: "avatar", id: "post-avatar", alt: "avatar")%><h6><%= post.user.username.capitalize %></h6>
      <% if post.photo %>
        <h5><%= post.content %></h5>
        <%= image_tag(post.photo, class: "post-img") if post.photo.attached?%>
      <% elsif post.video %>
        <p><%= post.content %></p>
        <%= video_tag(post.video) %>
      <% else %>
        <h5><%= post.content %></h5>
      <% end %>
      <%= link_to "Delete", post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      <small><%= Time.now %></small>
       <%# <small class="text-right flex-shrink-0"><%= link_to 'delete', community_posts_path(post), method: :delete, data: { confirm: "Are you sure you want to remove #{post}"}, class: 'text-danger' %>
    <hr class="hr">
    <% end %>
  </div>

  <div class="stuffs">
    <!-- Button trigger modal -->
    <div>
      <%# <button type="button" href="" class="match-btn" data-toggle="modal" data-target="#exampleModal">FIND MATCH</button> %>
      <%= link_to "Find Match", community_matches_path(@community), method: :post, class:"match-btn" %>
    </div>

      <div class="cmt-feature">
        <h4>Members</h4>
        <% @community.memberships.each do |membership| %>
        <%= link_to image_tag(membership.user.avatar_thumbnail, class: "avatar", id: "post-avatar", alt: "avatar"), profile_path(membership.user) %>
        <%# <small><%= membership.user.username.capitalize %>
        
        <% end %>
      </div>

      <%# <div class="cmt-feature2">
      </div> %>
  </div>
</div>